import type { Metadata } from "next";
import { Be_Vietnam_Pro, Inter, Karla } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });
// const beV = Be_Vietnam_Pro({ subsets: ["latin"] , weight: ["300","400", "500", "600", "700"]});
const karla = Karla({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={karla.className}>
        <Header />
        <main className="flex-1 h-full">{children}</main>
      </body>
    </html>
  );
}
